version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: llmpress-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  llmpress-worker:
    build:
      context: ${LLMPRESS_ROOT:-../AI}
      dockerfile: Dockerfile
    image: llmpress-worker:latest
    volumes:
      - ${LLMPRESS_ROOT:-../AI}:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    # Command is now defined in the Dockerfile with the entrypoint
    runtime: nvidia  # Older Docker Compose versions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles: ["gpu"]
    
  backend:
    build:
      context: ..
      dockerfile: Backend/Dockerfile
    volumes:
      - ../Backend:/app/Backend
      - ${LLMPRESS_ROOT:-../AI}:/app/AI
    environment:
      - PYTHONPATH=/app:/app/AI
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - llmpress-worker
    restart: unless-stopped
    profiles: ["gpu"]
    working_dir: /app/Backend

volumes:
  redis_data: